/* App entry and interface translations; no generation or publishing on page load. */
Object.assign(window.ORB_SPANISH || (window.ORB_SPANISH = {}), {
  "Looking for the earlier tools?": "¿Buscas las herramientas anteriores?",
  "For saved files and established workflows. New explorations start in the app.": "Para archivos guardados y formas de trabajo anteriores. Las nuevas exploraciones empiezan en la app.",
  "File Studio": "Studio de archivos",
  "ORB Share file tool": "Herramienta de archivos ORB Share",
  "ORB prompt": "Instrucciones ORB",
  "ORB skills": "Habilidades ORB",
  "Get started": "Primeros pasos",
  "Orbiversity · Explore, read, listen": "Orbiversity · Explora, lee, escucha",
  "Collection": "Colección",
  "About": "Acerca de",
  "Open the app ↗": "Abrir la app ↗",
  "Follow a question. Find a new direction.": "Sigue una pregunta. Descubre otra dirección.",
  "A quick introduction": "Una introducción rápida",
  "Explore, listen, and share discoveries in the ORB app.": "Explora, escucha y comparte descubrimientos en la app ORB.",
  "The collection": "La colección",
  "Published ORBs, guided recordings, and films.": "ORBs publicados, grabaciones guiadas y películas.",
  "Earlier shared ORBs": "ORBs compartidos anteriormente",
  "These existing links remain available. For new discoveries and sharing, open the app.": "Estos enlaces siguen disponibles. Para nuevos descubrimientos y para compartir, abre la app.",
  "Make your next discovery": "Haz tu próximo descubrimiento",
  "Ask a question in the app. Follow its connections, check the sources, and choose what to share.": "Haz una pregunta en la app. Sigue sus conexiones, consulta las fuentes y elige qué compartir.",
  "A subject becomes a place to explore.": "Un tema se convierte en un lugar para explorar.",
  "ORB connects a clear reading with the ideas around it.": "ORB conecta una lectura clara con las ideas que la rodean.",
  "Explore in the app": "Explora en la app",
  "Start with a question or a subject. Read the first answer, follow a related idea, and return to the places you visited.": "Empieza con una pregunta o un tema. Lee la primera respuesta, sigue una idea relacionada y vuelve a los lugares que visitaste.",
  "Use the reading route or open the map. Listen with available device voices, explore sources, and share a saved discovery when you choose.": "Sigue el recorrido de lectura o abre el mapa. Escucha con las voces disponibles en tu dispositivo, consulta fuentes y comparte un descubrimiento guardado cuando quieras.",
  "AI-generated readings can be mistaken. Check the linked sources before relying on a claim.": "Las lecturas generadas por IA pueden contener errores. Consulta las fuentes enlazadas antes de confiar en una afirmación.",
  "Read, listen, or watch the collection": "Lee, escucha o mira la colección",
  "The website holds published ORBs and their recordings. Each one keeps its own readings, sources, and available media.": "El sitio reúne ORBs publicados y sus grabaciones. Cada uno conserva sus lecturas, fuentes y medios disponibles.",
  "A recorded learning course where available.": "Un curso de aprendizaje grabado, cuando esté disponible.",
  "A guided listening journey where available.": "Un recorrido de escucha guiada, cuando esté disponible.",
  "Browse the collection →": "Explorar la colección →",
  "About Orbiversity": "Acerca de Orbiversity",
  "Start with one question.": "Empieza con una pregunta.",
  "The ORB app opens in your browser, on a phone or computer.": "La app ORB se abre en tu navegador, en el móvil o en el ordenador.",
  "Open the app": "Abre la app",
  "Type a subject or an ordinary question. Choose Explore when you are ready.": "Escribe un tema o una pregunta. Elige Explorar cuando estés listo.",
  "Follow what interests you": "Sigue lo que te interesa",
  "Read an answer, check its sources, and follow a connected idea. Use Back to return.": "Lee una respuesta, consulta sus fuentes y sigue una idea conectada. Usa Atrás para volver.",
  "Keep or share a discovery": "Guarda o comparte un descubrimiento",
  "Use the app’s save and sharing controls. Preview what will be shared before creating a link.": "Usa los controles para guardar y compartir de la app. Revisa lo que compartirás antes de crear un enlace.",
  "New research uses the app’s shared allowance. If it is unavailable, you can still browse the published collection.": "Las nuevas investigaciones usan el cupo compartido de la app. Si no está disponible, puedes seguir explorando la colección publicada.",
  "Get started · Orbiversity": "Primeros pasos · Orbiversity",
  "Orbiversity home": "Inicio de Orbiversity",
  "Earlier tools": "Herramientas anteriores"
});
(()=>{const reveal=()=>{if(location.hash==="#star-navigator"){const section=document.getElementById("earlier-discoveries");if(section)section.open=true;}};window.addEventListener("hashchange",reveal);reveal();})();
