'use strict';
const $=id=>document.getElementById(id), controls={query:$('search'),topic:$('topic'),format:$('format'),mode:$('journey-mode'),sort:$('sort')};
let catalog=JSON.parse($('orb-catalog').textContent).orbs;
function options(){const current=controls.topic.value;controls.topic.innerHTML='<option value="all">All topics</option>'+[...new Set(activeOrbs(catalog).map(o=>o.category).filter(Boolean))].sort().map(t=>'<option value="'+escapeHtml(t)+'">'+escapeHtml(t)+'</option>').join('');controls.topic.value=[...controls.topic.options].some(o=>o.value===current)?current:'all';const modes=[...new Set(activeOrbs(catalog).flatMap(journeyModes))].sort(),selected=controls.mode.value;controls.mode.innerHTML='<option value="all">All courses</option>'+modes.map(m=>'<option value="'+m+'">'+escapeHtml(courseModeLabel(m))+'</option>').join('');controls.mode.value=modes.includes(selected)?selected:'all';$('mode-field').hidden=!modes.length;}
function state(){return Object.fromEntries(Object.entries(controls).map(([key,element])=>[key,element.value]));}
function updateURL(){try{const url=new URL(location.href);for(const [key,value]of Object.entries(state())){const name=key==='query'?'q':key;if(value&&value!=='all'&&!(key==='sort'&&value==='updated'))url.searchParams.set(name,value);else url.searchParams.delete(name);}history.replaceState(null,'',url);}catch{}}
function render(){const rows=filterCatalog(catalog,state()),total=activeOrbs(catalog).length; $('entries').innerHTML=rows.map(renderOrbEntry).join('');$('empty').hidden=!!rows.length;$('count').textContent=rows.length===total?total+' '+(total===1?'ORB':'ORBs'):rows.length+' of '+total+' ORBs';updateURL();}
function reset(){controls.query.value='';controls.topic.value='all';controls.format.value='all';controls.mode.value='all';controls.sort.value='updated';render();controls.query.focus();}
function restoreURL(){const params=new URLSearchParams(location.search);for(const[key,element]of Object.entries(controls)){const value=params.get(key==='query'?'q':key);if(value!=null&&(element.tagName==='INPUT'||[...element.options].some(o=>o.value===value)))element.value=value;}}
document.querySelector('form.toolbar').addEventListener('submit',e=>e.preventDefault());controls.query.addEventListener('input',render);for(const[key,element]of Object.entries(controls))if(key!=='query')element.addEventListener('change',render);$('clear').addEventListener('click',reset);$('empty-reset').addEventListener('click',reset);
options();restoreURL();render();
window.addEventListener('popstate',()=>{controls.query.value='';controls.topic.value=controls.format.value=controls.mode.value='all';controls.sort.value='updated';restoreURL();render();});
if(location.protocol!=='file:')fetch('orbs.json',{cache:'no-cache'}).then(r=>{if(!r.ok)throw Error('Catalog unavailable');return r.json();}).then(data=>{if(!Array.isArray(data.orbs)||!data.orbs.every(o=>o&&typeof o.title==='string'&&Array.isArray(o.editions)))throw Error('Invalid catalog');catalog=data.orbs;options();restoreURL();render();}).catch(()=>{$('catalog-status').textContent='Showing the saved catalog. Refresh to check for newer entries.';$('catalog-status').hidden=false;});
