Object.assign(window.ORB_SPANISH||(window.ORB_SPANISH={}),{
 'Orbiversity · A vault of connected ORBs':'Orbiversity · Un archivo de ORBs conectados',
 'The collection':'La colección','Follow an orb. Find a connection.':'Sigue un orb. Encuentra una conexión.',
 'Saved readings · Linked editions':'Lecturas guardadas · Ediciones enlazadas','View the catalog':'Ver el catálogo','Add to Orbiversity':'Añadir a Orbiversity','The vault':'El archivo','Published ORBs':'ORBs publicados','Topic':'Tema','Format':'Formato','Sort by':'Ordenar por',
 'No ORBs match these filters.':'Ningún ORB coincide con estos filtros.','Show the collection':'Mostrar la colección','Open ORB':'Abrir ORB','Editions & sources':'Ediciones y fuentes',
 'Every edition keeps its readings, sources, and available recordings. Follow its links to continue exploring.':'Cada edición conserva sus lecturas, fuentes y grabaciones disponibles. Sigue sus enlaces para continuar explorando.',
 'Open any orb to read its published edition. No AI account or token key is needed to browse.':'Abre cualquier orb para leer su edición publicada. No necesitas una cuenta de IA ni una clave de acceso para explorar.',
 'How to browse':'Cómo explorar','Open an ORB file':'Abrir un archivo ORB','Contribute an ORB':'Contribuir un ORB','A collection you can explore.':'Una colección para explorar.',
 'Orbiversity holds published ORBs: readings, sources, and paths into other subjects.':'Orbiversity reúne ORBs publicados: lecturas, fuentes y caminos hacia otros temas.',
 'Follow what is already here':'Sigue lo que ya está aquí','Choose an orb in the browsing window or catalog. Open its saved edition, move among its readings, and follow its source links. Browsing the collection does not require a prompt, an AI account, or a token key.':'Elige un orb en la ventana de exploración o en el catálogo. Abre su edición guardada, recorre sus lecturas y sigue sus fuentes. No necesitas escribir una consulta, tener una cuenta de IA ni una clave de acceso.',
 'Read, listen, and watch':'Lee, escucha y mira','Each edition lists what it includes. Some offer recorded learning courses, guided audio journeys, or companion films. Readings may be written by people or created with AI assistance; the edition keeps its authorship and source information.':'Cada edición indica lo que incluye. Algunas ofrecen cursos grabados, recorridos de audio o películas. Las lecturas pueden ser escritas por personas o con ayuda de IA; cada edición conserva su autoría y sus fuentes.',
 'Linked images, recordings, and external sources may need an internet connection.':'Las imágenes, grabaciones y fuentes externas enlazadas pueden necesitar conexión a internet.','Grow the collection together':'Hagamos crecer la colección','Contribute a finished ORB for owner review. New contributions are checked before joining the collection. Related editions keep their creator credits and original links.':'Envía un ORB terminado para que lo revise el propietario. Las nuevas contribuciones se revisan antes de incorporarse. Las ediciones relacionadas conservan sus créditos y enlaces originales.',
 'Start with an orb.':'Empieza con un orb.','No setup. Choose a subject that catches your attention.':'Sin configuración. Elige un tema que te llame la atención.','Choose a saved ORB':'Elige un ORB guardado','Select a sphere in the browsing window, or follow a title in the catalog. Topic and format filters help narrow the collection.':'Selecciona una esfera en la ventana de exploración o un título del catálogo. Los filtros de tema y formato permiten acotar la colección.',
 'Follow its readings and sources':'Sigue sus lecturas y fuentes','Use the edition’s own orb controls and links. Included recordings and films are marked in the catalog.':'Usa los controles y enlaces de la edición. Las grabaciones y películas incluidas se indican en el catálogo.','Return and try another path':'Vuelve y prueba otro camino','Use your browser’s Back button to return to the vault. Versions & sources lists the earlier editions and their provenance.':'Usa el botón Atrás del navegador para volver al archivo. Versiones y fuentes muestra las ediciones anteriores y su procedencia.',
 'Have an ORB file?':'¿Tienes un archivo ORB?','The File Studio opens supported saved ORB files locally in your browser.':'File Studio abre archivos ORB compatibles de forma local en el navegador.','Open File Studio →':'Abrir File Studio →',
 'Share a finished ORB with the collection.':'Comparte un ORB terminado con la colección.','Submit for owner review':'Enviar para revisión del propietario','The current submission route uses GitHub. Share a published link or attach an ORB file, with a title, short description, and creator credit. A GitHub account is required.':'El envío actual se realiza por GitHub. Comparte un enlace publicado o adjunta un archivo ORB con título, descripción breve y crédito del creador. Se necesita una cuenta de GitHub.','Your submission and attachments on GitHub are public. Include only material you have permission to share.':'Tu envío y los archivos adjuntos en GitHub son públicos. Incluye únicamente material que tengas permiso para compartir.','Prepare a submission ↗':'Preparar un envío ↗','Submitting does not publish your ORB. The owner reviews each contribution before it joins the vault.':'Enviar no publica tu ORB. El propietario revisa cada contribución antes de incorporarla al archivo.',
 'What to include':'Qué incluir','A complete ORB with readable points and working links.':'Un ORB completo con puntos legibles y enlaces que funcionen.','Creator credit, source links, and permission to host the submitted edition.':'Crédito del creador, fuentes y permiso para alojar la edición enviada.','Any images or recordings the edition needs, with their credits.':'Las imágenes o grabaciones necesarias, con sus créditos.','After review':'Después de la revisión','Accepted editions keep their original credit and provenance. Related ORBs can be grouped without erasing the different perspectives or sources they contain.':'Las ediciones aceptadas conservan sus créditos y procedencia. Los ORBs relacionados pueden agruparse sin borrar sus diferentes perspectivas o fuentes.','Return to the collection →':'Volver a la colección →','Explore the collection.':'Explora la colección.','Orbiversity is the home for finished, linked ORBs.':'Orbiversity reúne ORBs terminados y enlazados.','Reading needs no AI connection':'Leer no requiere conexión con IA','Open a published edition and follow its included readings and sources.':'Abre una edición publicada y sigue sus lecturas y fuentes.'
});
