Object.assign(window.ORB_SPANISH||(window.ORB_SPANISH={}),{
 'Orbiversity · A vault of connected ORBs':'Orbiversity · Un archivo de ORBs conectados',
 'The collection':'La colección','Follow an orb. Find a connection.':'Sigue un orb. Encuentra una conexión.',
 'Saved readings · Linked editions':'Lecturas guardadas · Ediciones enlazadas','View the catalog':'Ver el catálogo','Add to Orbiversity':'Añadir a Orbiversity','The vault':'El archivo','Published ORBs':'ORBs publicados','Topic':'Tema','Format':'Formato','Sort by':'Ordenar por',
 'No ORBs match these filters.':'Ningún ORB coincide con estos filtros.','Show the collection':'Mostrar la colección','Open ORB':'Abrir ORB','Editions & sources':'Ediciones y fuentes',
 'Every edition keeps its readings, sources, and available recordings. Follow its links to continue exploring.':'Cada edición conserva sus lecturas, fuentes y grabaciones disponibles. Sigue sus enlaces para continuar explorando.',
 'Open any orb to read its published edition. No AI account or token key is needed to browse.':'Abre cualquier orb para leer su edición publicada. No necesitas una cuenta de IA ni una clave de acceso para explorar.',
 'How to browse':'Cómo explorar','Open an ORB file':'Abrir un archivo ORB','Contribute an ORB':'Contribuir un ORB','A collection you can explore.':'Una colección para explorar.',
 'Orbiversity holds published ORBs: readings, sources, and paths into other subjects.':'Orbiversity reúne ORBs publicados: lecturas, fuentes y caminos hacia otros temas.',
 'Follow what is already here':'Sigue lo que ya está aquí','Choose an orb in the browsing window or catalog. Open its saved edition, move among its readings, and follow its source links. Browsing the collection does not require a prompt, an AI account, or a token key.':'Elige un orb en la ventana de exploración o en el catálogo. Abre su edición guardada, recorre sus lecturas y sigue sus fuentes. No necesitas escribir una consulta, tener una cuenta de IA ni una clave de acceso.',
 'Read, listen, and watch':'Lee, escucha y mira','Each edition lists what it includes. Some offer recorded learning courses, guided audio journeys, or companion films. Readings may be written by people or created with AI assistance; the edition keeps its authorship and source information.':'Cada edición indica lo que incluye. Algunas ofrecen cursos grabados, recorridos de audio o películas. Las lecturas pueden ser escritas por personas o con ayuda de IA; cada edición conserva su autoría y sus fuentes.',
 'Linked images, recordings, and external sources may need an internet connection.':'Las imágenes, grabaciones y fuentes externas enlazadas pueden necesitar conexión a internet.','Grow the collection together':'Hagamos crecer la colección','Contribute a finished ORB for owner review. New contributions are checked before joining the collection. Related editions keep their creator credits and original links.':'Envía un ORB terminado para que lo revise el propietario. Las nuevas contribuciones se revisan antes de incorporarse. Las ediciones relacionadas conservan sus créditos y enlaces originales.',
 'Start with an orb.':'Empieza con un orb.','No setup. Choose a subject that catches your attention.':'Sin configuración. Elige un tema que te llame la atención.','Choose a saved ORB':'Elige un ORB guardado','Select a sphere in the browsing window, or follow a title in the catalog. Topic and format filters help narrow the collection.':'Selecciona una esfera en la ventana de exploración o un título del catálogo. Los filtros de tema y formato permiten acotar la colección.',
 'Follow its readings and sources':'Sigue sus lecturas y fuentes','Use the edition’s own orb controls and links. Included recordings and films are marked in the catalog.':'Usa los controles y enlaces de la edición. Las grabaciones y películas incluidas se indican en el catálogo.','Return and try another path':'Vuelve y prueba otro camino','Use your browser’s Back button to return to the vault. Versions & sources lists the earlier editions and their provenance.':'Usa el botón Atrás del navegador para volver al archivo. Versiones y fuentes muestra las ediciones anteriores y su procedencia.',
 'Have an ORB file?':'¿Tienes un archivo ORB?','The File Studio opens supported saved ORB files locally in your browser.':'File Studio abre archivos ORB compatibles de forma local en el navegador.','Open File Studio →':'Abrir File Studio →',
 'Share a finished ORB with the collection.':'Comparte un ORB terminado con la colección.','Submit for owner review':'Enviar para revisión del propietario','The current submission route uses GitHub. Share a published link or attach an ORB file, with a title, short description, and creator credit. A GitHub account is required.':'El envío actual se realiza por GitHub. Comparte un enlace publicado o adjunta un archivo ORB con título, descripción breve y crédito del creador. Se necesita una cuenta de GitHub.','Your submission and attachments on GitHub are public. Include only material you have permission to share.':'Tu envío y los archivos adjuntos en GitHub son públicos. Incluye únicamente material que tengas permiso para compartir.','Prepare a submission ↗':'Preparar un envío ↗','Submitting does not publish your ORB. The owner reviews each contribution before it joins the vault.':'Enviar no publica tu ORB. El propietario revisa cada contribución antes de incorporarla al archivo.',
 'What to include':'Qué incluir','A complete ORB with readable points and working links.':'Un ORB completo con puntos legibles y enlaces que funcionen.','Creator credit, source links, and permission to host the submitted edition.':'Crédito del creador, fuentes y permiso para alojar la edición enviada.','Any images or recordings the edition needs, with their credits.':'Las imágenes o grabaciones necesarias, con sus créditos.','After review':'Después de la revisión','Accepted editions keep their original credit and provenance. Related ORBs can be grouped without erasing the different perspectives or sources they contain.':'Las ediciones aceptadas conservan sus créditos y procedencia. Los ORBs relacionados pueden agruparse sin borrar sus diferentes perspectivas o fuentes.','Return to the collection →':'Volver a la colección →','Explore the collection.':'Explora la colección.','Orbiversity is the home for finished, linked ORBs.':'Orbiversity reúne ORBs terminados y enlazados.','Reading needs no AI connection':'Leer no requiere conexión con IA','Open a published edition and follow its included readings and sources.':'Abre una edición publicada y sigue sus lecturas y fuentes.'
});
Object.assign(window.ORB_SPANISH,{
 'Orbiversity - HTML Orb Museum':'Orbiversity - Museo de orbs HTML','HTML Orb Museum':'Museo de orbs HTML','The museum':'El museo','Add an ORB':'Añadir un ORB','A community museum':'Un museo de la comunidad','Worlds worth exploring.':'Mundos que vale la pena explorar.','Read. Listen. Follow a real source.':'Lee. Escucha. Sigue una fuente real.','Connected ideas. A shared world.':'Ideas conectadas. Un mundo compartido.','Visit the collection':'Visita la colección','Enter this ORB':'Entra en este ORB','Reality Gallery, recordings & editions':'Galería de la Realidad, grabaciones y ediciones','Also inside':'También encontrarás','A finished world of readings and real sources. Follow its links at your own pace.':'Un mundo terminado de lecturas y fuentes reales. Sigue sus enlaces a tu propio ritmo.',
 'The permanent collection':'La colección permanente','Explore the museum':'Explora el museo','Reality Gallery & recordings':'Galería de la Realidad y grabaciones','Reality Gallery & sources':'Galería de la Realidad y fuentes','Listen to this edition':'Escucha esta edición','Edition source files':'Archivos fuente de la edición','Image library & credits':'Galería de la Realidad de imágenes y créditos','Built together':'Creado en comunidad','There is room for your world.':'Hay espacio para tu mundo.','Contribute a finished orb with its library and recordings. Keep your perspective. Add your signature.':'Comparte un orb terminado con su galería de la realidad y sus grabaciones. Conserva tu perspectiva. Añade tu firma.','Every edition keeps its readings, sources, and available recordings. Earlier works remain part of the collection.':'Cada edición conserva sus lecturas, fuentes y grabaciones disponibles. Las obras anteriores siguen formando parte de la colección.','A community collection · By Informational Dimensions':'Una colección de la comunidad · Por Informational Dimensions','About the museum':'Acerca del museo','How to explore':'Cómo explorar',
 'Contribute to the museum':'Contribuye al museo','Give your orb a home.':'Dale un hogar a tu orb.','Bring its readings, Reality Gallery, and recordings together. Sign it if you like.':'Reúne sus lecturas, galería de la realidad y grabaciones. Fírmalo si quieres.','Prepared on your device. Published only after owner review.':'Preparado en tu dispositivo. Se publica solo tras la revisión del propietario.','Already exported a museum package?':'¿Ya exportaste un paquete para el museo?','If you have a review ZIP from the ORB app, you can skip this form.':'Si tienes un ZIP de revisión de la app ORB, puedes saltarte este formulario.','Take your package to manual review':'Lleva tu paquete a revisión manual',
 'Your contribution':'Tu contribución','ORB title':'Título del ORB','Required':'Obligatorio','A short introduction':'Una breve introducción','Sign your orb':'Firma tu orb','Optional':'Opcional','The name of your world':'El nombre de tu mundo','What will someone discover here?':'¿Qué descubrirán aquí?','Your name, studio, or chosen signature':'Tu nombre, estudio o firma elegida','The public creator credit you would like to appear with your orb. You can leave it blank.':'El crédito público que quieres que aparezca con tu orb. Puedes dejarlo en blanco.','The complete edition':'La edición completa','The HTML orb':'El orb HTML','Your finished .html file · up to 32 MB':'Tu archivo .html terminado · hasta 32 MB','Choose your HTML file':'Elige tu archivo HTML','ORB data':'Datos del ORB','Its .json file, if you have one · up to 8 MB':'Su archivo .json, si lo tienes · hasta 8 MB','No data file selected':'No has elegido un archivo de datos','Recordings':'Grabaciones','Narration or music used by this edition.':'Narración o música utilizada por esta edición.','Choose audio files':'Elige archivos de audio','Reality Gallery files':'Archivos de galería de la realidad','Images, documents, videos, styles, and other local files the orb uses.':'Imágenes, documentos, vídeos, estilos y otros archivos locales que utiliza el orb.','Choose supporting files':'Elige archivos de apoyo','Include the local files your HTML refers to. External sources keep their links. Up to 256 files and 256 MB total; individual supporting files can be up to 128 MB.':'Incluye los archivos locales que utiliza tu HTML. Las fuentes externas conservan sus enlaces. Hasta 256 archivos y 256 MB en total; cada archivo de apoyo puede tener hasta 128 MB.','Files in this contribution':'Archivos de esta contribución',
 'Reality Gallery links & credits':'Enlaces de galería de la realidad y créditos','Add source collections, credits, or other materials visitors should find with your orb.':'Añade colecciones de fuentes, créditos u otros materiales que acompañen tu orb.','+ Add a source link':'+ Añadir enlace a una fuente','Source title':'Título de la fuente','Link':'Enlace','Type':'Tipo','A source, collection, or credit':'Una fuente, colección o crédito','Source':'Fuente','Images':'Imágenes','Book':'Libro','Audio':'Audio','Document':'Documento','Credits':'Créditos','Remove':'Quitar','I have permission to share this orb and the materials I include.':'Tengo permiso para compartir este orb y los materiales que incluyo.','Prepare review package':'Preparar paquete de revisión','Ready for review':'Listo para revisar','Your orb travels together.':'Tu orb viaja completo.','Download package':'Descargar paquete','Download contents list':'Descargar lista de contenidos','Nothing has been sent or published. Download your package, then open the manual review page to share it with the museum.':'No se ha enviado ni publicado nada. Descarga tu paquete y abre la página de revisión manual para compartirlo con el museo.','Open manual review':'Abrir revisión manual','A place in the collection':'Un lugar en la colección','Keep the whole story.':'Conserva toda la historia.','A museum orb carries its readings, source paths, and the materials that make it yours.':'Un orb del museo lleva sus lecturas, caminos hacia las fuentes y los materiales que lo hacen tuyo.','Prepare':'Preparar','Review':'Revisar','Connect':'Conectar','Gather the finished HTML and its supporting files.':'Reúne el HTML terminado y sus archivos de apoyo.','The owner checks the edition, credits, and its connections to the collection.':'El propietario revisa la edición, los créditos y sus conexiones con la colección.','Accepted orbs gain a place in the museum and paths to related subjects.':'Los orbs aceptados encuentran un lugar en el museo y caminos hacia temas relacionados.','How review works today':'Cómo funciona la revisión hoy','The current review queue uses GitHub. It requires a GitHub account, and submissions and attachments there are public. Downloading here does not send your files.':'La revisión actual utiliza GitHub. Se requiere una cuenta de GitHub y los envíos y archivos adjuntos son públicos. Descargar aquí no envía tus archivos.','The museum keeps older editions available. Historical works do not need to be rebuilt to satisfy the new package format.':'El museo conserva las ediciones anteriores. Las obras históricas no necesitan rehacerse para cumplir el nuevo formato de paquete.',
 'A museum of connected worlds.':'Un museo de mundos conectados.','A place to keep what people have explored, made, and learned — and to find a path into it.':'Un lugar para conservar lo que las personas han explorado, creado y aprendido, y encontrar un camino hacia ello.','Each orb is a finished work':'Cada orb es una obra terminada','The library belongs with the orb':'La galería de la realidad forma parte del orb','Made by a community':'Creado por una comunidad','Visit the museum →':'Visita el museo →','Choose a subject that catches your attention. Everything here is already made.':'Elige un tema que te llame la atención. Todo lo que hay aquí ya está creado.','Enter a world':'Entra en un mundo','Follow the material':'Sigue el material','Find another connection':'Encuentra otra conexión','Have a saved ORB file?':'¿Tienes un archivo ORB guardado?','File Studio opens supported ORB data locally in your browser.':'File Studio abre datos ORB compatibles localmente en tu navegador.','The museum is open.':'El museo está abierto.','Finished orbs, real source paths, and new connections.':'Orbs terminados, caminos hacia fuentes reales y nuevas conexiones.','Explore at your own pace':'Explora a tu propio ritmo'
});

Object.assign(window.ORB_SPANISH,{
 'Images, documents, MP4/WebM, and CSS/JS files the orb uses.':'Imágenes, documentos, archivos MP4/WebM y CSS/JS que utiliza el orb.',
 'Attach a ZIP up to 25 MB. For a larger package, share a public download link in the review form.':'Adjunta un ZIP de hasta 25 MB. Para un paquete mayor, comparte un enlace público de descarga en el formulario de revisión.',
 'GitHub attachment limits':'Límites de archivos adjuntos de GitHub',
 'Your package is larger than GitHub’s 25 MB attachment limit. It is kept intact. Upload it to a public download location you trust, then paste that download link into the manual review form.':'Tu paquete supera el límite de 25 MB de archivos adjuntos de GitHub. Se conserva completo. Súbelo a un lugar de descarga pública de confianza y pega el enlace en el formulario de revisión manual.'
});
Object.assign(window.ORB_SPANISH,{
 'Bring its readings, Reality Gallery, and recordings together. Add your perspective and choose how to be credited.':'Reúne sus lecturas, galería de la realidad y grabaciones. Añade tu perspectiva y elige cómo aparecer en los créditos.',
 'How should it be credited?':'¿Cómo quieres aparecer en los créditos?','Anonymous':'Anónimo','With a name':'Con un nombre','Your public name':'Tu nombre público',
 'Anonymous credit does not remove names from your uploaded files or notes. The manual review uses your public GitHub account.':'El crédito anónimo no elimina nombres de los archivos o notas que subas. La revisión manual utiliza tu cuenta pública de GitHub.',
 'About this orb':'Acerca de este orb','A special point for your personal note and how you would like the orb experienced. Both are optional and will be public with the orb.':'Un punto especial para tu nota personal y cómo te gustaría que se viviera el orb. Ambos son opcionales y se publicarán con el orb.',
 'A personal note':'Una nota personal','What brought you to this subject? What would you like someone to know?':'¿Qué te llevó a este tema? ¿Qué te gustaría que los demás supieran?',
 'How would you like this orb expressed?':'¿Cómo te gustaría que se expresara este orb?','Describe the mood, perspective, or way you hope people will explore it.':'Describe el ambiente, la perspectiva o la forma en que te gustaría que se explorara.',
 'Your words stay with the contribution. They guide its presentation; they do not automatically rewrite the orb.':'Tus palabras acompañan la contribución. Orientan su presentación; no reescriben el orb automáticamente.',
 'Public preview':'Vista previa pública','How I hope you experience this orb':'Cómo espero que vivas este orb','Your note and preferred presentation will appear here when you add them.':'Tu nota y la presentación que prefieres aparecerán aquí cuando las añadas.',
 'Your orb — an anonymous orb':'Tu orb — un orb anónimo'
});
Object.assign(window.ORB_SPANISH,{
 'Collection':'Colección','The collection':'La colección','Explore ORB free':'Explora ORB gratis','Explore the Orbiverse.':'Explora el Orbiverso.','A living collection of readings, recordings, and real sources.':'Una colección viva de lecturas, grabaciones y fuentes reales.',
 'Share your work':'Comparte tu trabajo','Profile links':'Enlaces de perfil','Your work & ideas':'Tu trabajo e ideas',
 'Add public profile links, or share an idea, thought, project, design, or product. These stay with your orb, separate from its sources.':'Añade perfiles públicos o comparte una idea, reflexión, proyecto, diseño o producto. Acompañan a tu orb, separados de sus fuentes.',
 'Only add links and words you want published. Profile links can identify you even when your orb has anonymous credit.':'Añade solo enlaces y palabras que quieras publicar. Los perfiles pueden identificarte aunque el orb tenga crédito anónimo.',
 '+ Add a profile link':'+ Añadir un enlace de perfil','+ Add work or an idea':'+ Añadir trabajo o una idea','Clear shared work':'Borrar el trabajo compartido',
 'Up to six profile links and six entries. Ideas can be words alone; links must be public HTTPS addresses without sign-in tokens.':'Hasta seis perfiles y seis entradas. Las ideas pueden ser solo palabras; los enlaces deben ser direcciones HTTPS públicas sin claves de acceso.',
 'Profile label':'Nombre del perfil','Public profile link':'Enlace al perfil público','Kind':'Tipo','Title':'Título','A few words':'Unas palabras','Public link (optional)':'Enlace público (opcional)',
 'Idea':'Idea','Thought':'Reflexión','Project':'Proyecto','Design':'Diseño','Product':'Producto','From the contributor':'De quien contribuye',
 'Shared work and profile links, separate from this orb’s sources.':'Trabajo y perfiles compartidos, separados de las fuentes de este orb.'
});
Object.assign(window.ORB_SPANISH||(window.ORB_SPANISH={}),{
 'The original collection is ready. Loading community orbs…':'La colección original está lista. Cargando orbs de la comunidad…',
 'Try again':'Intentar de nuevo','Publish directly from ORB, or keep a complete package of an older HTML edition.':'Publica directamente desde ORB o conserva un paquete completo de una edición HTML anterior.',
 'Already exploring in ORB?':'¿Ya estás explorando en ORB?',
 'Choose Add your orb to the Museum in the ORB app. Your readings, Reality Gallery and saved media publish together. Choose anonymous credit or add your name and personal note. Up to three new orbs per day in this browser.':'Elige Añadir tu orb al Museo en la aplicación ORB. Tus lecturas, galería de la realidad y medios guardados se publican juntos. Elige crédito anónimo o añade tu nombre y una nota personal. Hasta tres orbs nuevos al día en este navegador.',
 'Open ORB →':'Abrir ORB →','Keep an older HTML edition together':'Conserva completa una edición HTML anterior',
 'The form below makes a local package with its original HTML, recordings and supporting files. It does not publish or execute the HTML. Direct publishing is available from the ORB app.':'El formulario siguiente crea un paquete local con el HTML original, las grabaciones y los archivos complementarios. No publica ni ejecuta el HTML. Puedes publicar directamente desde la aplicación ORB.'
});

Object.assign(window.ORB_SPANISH||(window.ORB_SPANISH={}),{"Explore with Nano": "Explorar con Nano", "Explore with Nano →": "Explorar con Nano →", "Explore your own subject": "Explora tu propio tema", "Nano creates a new ORB on the website. Follow its branches, read, listen, and publish a finished edition to the museum when you choose.": "Nano crea un nuevo ORB en el sitio web. Sigue sus ramas, lee, escucha y publica una edición terminada en el museo cuando quieras."});
