'use strict';
(()=>{
 const catalog=JSON.parse(document.getElementById('orb-catalog').textContent).orbs,controls={topic:document.getElementById('topic'),format:document.getElementById('format'),sort:document.getElementById('sort')},form=document.querySelector('.vault-filters'),entries=document.getElementById('entries'),overview=document.getElementById('orb-overview');
 const state=()=>Object.fromEntries(Object.entries(controls).map(([key,value])=>[key,value.value]));
 function render(){const rows=filterCatalog(catalog,state());entries.innerHTML=rows.map(o=>renderOrbEntry(o).replace('<article class="orb-row"','<article id="orb-'+escapeHtml(o.id)+'" class="orb-row"')).join('');document.getElementById('empty').hidden=!!rows.length;document.getElementById('count').textContent=rows.length===catalog.length?catalog.length+' ORBs':rows.length+' of '+catalog.length+' ORBs';const url=new URL(location.href);for(const [key,value]of Object.entries(state()))value==='all'||key==='sort'&&value==='updated'?url.searchParams.delete(key):url.searchParams.set(key,value);history.replaceState(null,'',url);}
 const reset=()=>{controls.topic.value=controls.format.value='all';controls.sort.value='updated';render()};
 function restore(){const p=new URLSearchParams(location.search);for(const [key,el]of Object.entries(controls)){const value=p.get(key);el.value=[...el.options].some(o=>o.value===value)?value:key==='sort'?'updated':'all';}}
 form.hidden=false;form.addEventListener('submit',event=>event.preventDefault());Object.values(controls).forEach(c=>c.addEventListener('change',render));document.getElementById('clear').addEventListener('click',reset);document.getElementById('empty-reset').addEventListener('click',reset);window.addEventListener('popstate',()=>{restore();render()});restore();render();
 function preview(id){const o=catalog.find(o=>o.id===id);if(!o)return;const f=featured(o),a=availability(o);overview.setAttribute('aria-label',o.title);overview.innerHTML='<p class="eyebrow">'+escapeHtml(o.category||'From the collection')+'</p><h2>'+escapeHtml(o.title)+'</h2><p class="overview-description">'+escapeHtml(o.description)+'</p><p class="overview-meta">'+(pointCount(o)||'Included')+' readings'+(a.audio?' · Recorded audio':'')+(a.video?' · Film':'')+'</p><a class="primary-link" href="'+escapeHtml(f.url)+'">Open ORB <span aria-hidden="true">↗</span></a><a class="edition-link" href="#orb-'+escapeHtml(o.id)+'">Editions &amp; sources</a><p class="vault-note">Open any orb to read its published edition. No AI account or token key is needed to browse.</p>';}
 document.querySelectorAll('[data-orb]').forEach(a=>{a.addEventListener('pointerenter',event=>{if(event.pointerType==='mouse')preview(a.dataset.orb)});a.addEventListener('focus',()=>preview(a.dataset.orb));});
 overview.addEventListener('click',event=>{const link=event.target.closest('.edition-link');if(!link||event.button!==0||event.metaKey||event.ctrlKey||event.shiftKey||event.altKey)return;const id=new URL(link.href).hash.slice(1);event.preventDefault();if(!document.getElementById(id))reset();const target=document.getElementById(id);if(target){const url=new URL(location.href);url.hash=id;history.pushState(null,'',url);target.scrollIntoView({block:'start'});}});
})();
