/* Visitor guide translations; load before languages.js. */
Object.assign(window.ORB_SPANISH || (window.ORB_SPANISH = {}), {
  "Ways to use ORB": "Formas de usar ORB",
  "Ways to use ORB · Orbiversity": "Formas de usar ORB · Orbiversity",
  "One ORB. Five ways to explore.": "Un ORB. Cinco formas de explorar.",
  "Browse a finished exploration, or choose how to create your own.": "Explora una experiencia terminada o elige cómo crear la tuya.",
  "ORB turns a subject into connected ideas, illustrated readings and optional listening. These five routes explain where it runs, who supplies the AI, and what is ready today.": "ORB convierte un tema en ideas conectadas, lecturas ilustradas y opciones de escucha. Estas cinco rutas explican dónde funciona, quién proporciona la IA y qué está disponible hoy.",
  "New to ORB? Explore a saved ORB first →": "¿Es tu primera visita? Explora un ORB guardado →",
  "Choose a route": "Elige una ruta",
  "With ChatGPT": "Con ChatGPT",
  "With OpenRouter": "Con OpenRouter",
  "With a local LLM": "Con un modelo local",
  "Explore saved ORBs (HTML)": "Explora ORBs guardados (HTML)",
  "ORB Membership": "Membresía de ORB",
  "Private preview": "Vista previa privada",
  "Turn your conversation into an ORB.": "Convierte tu conversación en un ORB.",
  "The ChatGPT plugin direction connects ORB to a supported ChatGPT account. Ask about a topic, explore the result, and continue the conversation to create new directions.": "La ruta del complemento de ChatGPT conecta ORB con una cuenta compatible de ChatGPT. Pregunta sobre un tema, explora el resultado y continúa la conversación para crear nuevas direcciones.",
  "Who pays / the benefit": "Quién paga / la ventaja",
  "Text creation uses your available ChatGPT allowance, without a separate text-generation API account. Generated audio and other media may use separately funded services.": "La creación de texto utiliza tu uso disponible en ChatGPT, sin otra cuenta de API para generar texto. El audio generado y otros medios pueden utilizar servicios con financiación independiente.",
  "What to consider": "Qué tener en cuenta",
  "The embedded reader has limited space. In the separate website reader, follow-up prompts currently need to be taken back to ChatGPT. Features also depend on the host application.": "El lector integrado tiene espacio limitado. En el lector abierto como sitio web independiente, las solicitudes de seguimiento deben volver actualmente a ChatGPT. Las funciones también dependen de la aplicación que lo aloja.",
  "Where it stands": "Estado actual",
  "A private connection has been tested. A public directory listing is not yet available; setup depends on your ChatGPT account and workspace.": "Se ha probado una conexión privada. Todavía no hay una publicación en el directorio público; la configuración depende de tu cuenta y espacio de trabajo de ChatGPT.",
  "Read the connected-ORB guide ↗": "Lee la guía de ORB conectado ↗",
  "Planned integration": "Integración prevista",
  "Use the ORB website with your own AI credits.": "Usa el sitio web de ORB con tus propios créditos de IA.",
  "The planned connection would let you fund a personal OpenRouter account and create ORBs using supported models inside the ORB website.": "La conexión prevista te permitiría añadir fondos a una cuenta personal de OpenRouter y crear ORBs con modelos compatibles dentro del sitio web de ORB.",
  "You would pay OpenRouter for your model requests. This keeps personal AI spending under your control. OpenRouter credits are separate from a ChatGPT subscription and do not pay ORB a membership fee.": "Pagarías a OpenRouter por las solicitudes al modelo. Así controlarías tu gasto personal en IA. Los créditos de OpenRouter son independientes de una suscripción a ChatGPT y no pagan una membresía de ORB.",
  "You would need another account and a credit balance. Writing quality, speed and access to current information depend on the supported model and research tools.": "Necesitarías otra cuenta y un saldo de créditos. La calidad del texto, la velocidad y el acceso a información actual dependen del modelo compatible y de las herramientas de investigación.",
  "Personal account connection is still in development. Buying credits today does not automatically connect them to ORB.": "La conexión de cuentas personales sigue en desarrollo. Comprar créditos hoy no los conecta automáticamente con ORB.",
  "Learn about OpenRouter ↗": "Conoce OpenRouter ↗",
  "Experimental setup": "Configuración experimental",
  "Create with a model running on your computer.": "Crea con un modelo que se ejecuta en tu ordenador.",
  "This route pairs a local ORB installation with Ollama and a supported model, such as the prepared Gemma setup. It is for people comfortable installing and configuring software.": "Esta ruta combina una instalación local de ORB con Ollama y un modelo compatible, como la configuración de Gemma preparada. Está dirigida a personas que se sienten cómodas instalando y configurando software.",
  "Your hardware and electricity supply the text generation, avoiding per-request cloud-model charges. Optional online services can still have costs.": "Tu equipo y electricidad proporcionan la generación de texto, evitando cobros por cada solicitud a un modelo en la nube. Los servicios en línea opcionales pueden seguir teniendo costes.",
  "Speed and quality depend on your computer and model. The current local trial does not include live web research, cloud speech, online publishing or media lookup.": "La velocidad y calidad dependen de tu equipo y modelo. La prueba local actual no incluye investigación web en directo, voz en la nube, publicación en línea ni búsqueda de medios.",
  "The adapter and launch scripts are prepared; real-machine performance is still being checked. There is no tested public ORB installer yet. Ollama alone does not install ORB.": "El adaptador y los scripts de inicio están preparados; el rendimiento en un equipo real aún se está comprobando. Todavía no hay un instalador público de ORB probado. Ollama por sí solo no instala ORB.",
  "Learn about Ollama ↗": "Conoce Ollama ↗",
  "Available now": "Disponible ahora",
  "Open a finished ORB and follow your curiosity.": "Abre un ORB terminado y sigue tu curiosidad.",
  "Choose from the published collection. Move between prepared points, read the included passages, explore images and sources, and enjoy recordings where the edition includes them.": "Elige una experiencia de la colección publicada. Recorre los puntos preparados, lee los textos incluidos, explora imágenes y fuentes, y disfruta de grabaciones cuando la edición las incluya.",
  "You do not need an AI account or token balance to read and navigate these finished editions. No new model request is needed for that exploration.": "No necesitas una cuenta de IA ni saldo de tokens para leer y recorrer estas ediciones terminadas. Esa exploración no necesita nuevas solicitudes a un modelo.",
  "You explore the material already included. New answers, images or OrbCast episodes require a creation route. Downloaded HTML may still need the internet for external images, audio and links.": "Exploras el material ya incluido. Las nuevas respuestas, imágenes o episodios de OrbCast requieren una ruta de creación. El HTML descargado puede seguir necesitando internet para imágenes externas, audio y enlaces.",
  "The published collection is ready to browse. Original content may be AI-assisted; each edition retains its own sources and credits. Complete offline download packages are still being evaluated.": "La colección publicada ya se puede explorar. El contenido original puede haberse creado con ayuda de IA; cada edición conserva sus propias fuentes y créditos. Los paquetes completos para descarga sin conexión siguen en evaluación.",
  "Browse the saved collection →": "Explora la colección guardada →",
  "Planned service": "Servicio previsto",
  "One ORB account, with AI service included.": "Una cuenta de ORB, con servicio de IA incluido.",
  "The membership direction would let you sign into ORB and create without choosing an external provider or installing a local model. ORB would operate and fund the AI service.": "La ruta de membresía te permitiría iniciar sesión en ORB y crear sin elegir un proveedor externo ni instalar un modelo local. ORB operaría y financiaría el servicio de IA.",
  "Members would pay ORB. ORB would pay the model providers and the hosting, storage and media services included in the plan.": "Los miembros pagarían a ORB. ORB pagaría a los proveedores de modelos y los servicios de alojamiento, almacenamiento y medios incluidos en el plan.",
  "A recurring charge and a defined service allowance would apply. The aim is comfortable exploration with clear inclusions; unlimited generation has not been promised.": "Habría un cobro periódico y una cantidad definida de servicio. El objetivo es explorar con comodidad y saber qué está incluido; no se ha prometido generación ilimitada.",
  "Membership accounts, payments and pricing are not available yet. The existing app preview is not a paid membership product.": "Las cuentas de membresía, los pagos y los precios todavía no están disponibles. La vista previa existente de la aplicación no es un producto de membresía de pago.",
  "Start with a little curiosity.": "Empieza con un poco de curiosidad.",
  "A saved ORB is the easiest introduction: no setup, just a subject to explore. Try the illustrated Autumn collection, then choose a creation route when you are ready.": "Un ORB guardado es la introducción más sencilla: sin configuración, solo un tema para explorar. Prueba la colección ilustrada de otoño y elige una ruta de creación cuando quieras.",
  "Explore Autumn in the Pacific Northwest ↗": "Explora el otoño en el noroeste del Pacífico ↗",
  "Availability reviewed September 14, 2026. Voice, imagery and export features vary by route.": "Disponibilidad revisada el 14 de septiembre de 2026. Las funciones de voz, imágenes y exportación varían según la ruta.",
  "Compare all five ways to use ORB →": "Compara las cinco formas de usar ORB →",
  "Choose a finished HTML exploration, ChatGPT, personal OpenRouter credits, a local model or a future ORB membership.": "Elige una exploración HTML terminada, ChatGPT, créditos personales de OpenRouter, un modelo local o una futura membresía de ORB."
});
